### PR TITLE
mr-auth-form

### PR DESCRIPTION
**Pull request by MikepdXRider**
Users should see the sign-in form upon clicking 'sign in' or 'login' and upon submitting they are redirected to the Select Page

** Includes a useForm hook

### CODE REVIEW

**Comment by MikepdXRider** [comment]
image

**Review by k-schrattenholzer — APPROVED** [review]
This looks great!

**Review by EmilyDSarani — APPROVED** [review]
noice

**Review by diyanamendoza — APPROVED** [review]
:)

**Pull request merged**
